name: Publish

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  create-staging-repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository-id: ${{ steps.create.outputs.repository-id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@v1
        with:
          username: arkivanov
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          description: Created by GitHub Actions
  metadata-publish:
    name: Publish Metadata
    runs-on: ubuntu-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Metadata
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dpublish_metadata
  linux-publish:
    name: Publish on Linux
    runs-on: ubuntu-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish on Linux
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dtargets=ANDROID,JVM,JS_IR,JS_LEGACY,LINUX_X64
  macos-publish:
    name: Publish on macOS
    runs-on: macos-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish on macOS
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dtargets=IOS,WATCHOS,MACOS_X64
  close-staging-repository:
    name: Close staging repository
    runs-on: ubuntu-latest
    needs: [ create-staging-repository, metadata-publish, linux-publish, macos-publish ]
    steps:
      - name: Close staging repository
        uses: nexus-actions/release-nexus-staging-repo@v1.1
        with:
          username: arkivanov
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.create-staging-repository.outputs.repository-id }}
          close_only: 'true'
  linux-check-publication:
    name: Check publication on Linux
    runs-on: ubuntu-latest
    needs: close-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install nodejs chromium-browser
      - name: Check publication on Linux
        run: ./gradlew :tools:check-publication:build -Pcheck_publication -Dtargets=ANDROID,JVM,JS_IR,JS_LEGACY,LINUX_X64
  macos-check-publication:
    name: Check macOS publication
    runs-on: macos-latest
    needs: close-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check macOS publication
        run: ./gradlew :tools:check-publication:build -Pcheck_publication -Dtargets=IOS,WATCHOS,MACOS_X64
